package com.example.album.ui

import androidx.compose.runtime.compositionLocalOf

val LocalAppEnglish = compositionLocalOf { false }

fun appText(chinese: String, english: Boolean): String = if (english) APP_ENGLISH[chinese] ?: chinese else chinese

private val APP_ENGLISH = mapOf(
    "请输入文本" to "Enter text",
    "相册" to "Albums", "视频" to "Videos", "时间轴" to "Timeline", "设置" to "Settings",
    "返回" to "Back", "取消" to "Cancel", "确定" to "OK", "应用" to "Apply", "保存" to "Save", "保存副本" to "Save copy",
    "完成" to "Done", "关闭" to "Close", "知道了" to "Done", "添加" to "Add", "清除" to "Clear",
    "信息" to "Info", "编辑" to "Edit", "删除" to "Delete", "彻底删除" to "Delete permanently",
    "分享" to "Share", "复制" to "Copy", "移动" to "Move", "重命名" to "Rename",
    "打开方式" to "Open with", "设置为壁纸" to "Set as wallpaper", "幻灯片" to "Slideshow",
    "排除" to "Exclude", "更多操作" to "More actions", "全选" to "Select all", "取消全选" to "Deselect all",
    "收藏所选" to "Favorite selected", "删除所选" to "Delete selected", "复制所选" to "Copy selected",
    "移动所选" to "Move selected", "退出多选" to "Exit selection", "需要照片和视频访问权限" to "Photos and videos permission required",
    "需要照片访问权限" to "Photos permission required", "授权访问" to "Allow access",
    "授权后才能读取设备上的相册内容。" to "Allow access to read photos and videos on this device.",
    "没有找到相关内容" to "No matching items", "这里还没有图片" to "No photos yet", "这里还没有视频" to "No videos yet", "此文件夹没有内容" to "This folder is empty",
    "排序方式" to "Sort", "列数" to "Columns", "排布方式" to "Layout", "网格" to "Grid", "自适应" to "Adaptive",
    "时间" to "Date", "名称" to "Name", "大小" to "Size", "数量" to "Count", "时长" to "Duration",
    "升序" to "Ascending", "降序" to "Descending", "覆盖" to "Replace", "跳过" to "Skip", "保留两者" to "Keep both",
    "跳转日期" to "Jump to date", "排除文件夹" to "Exclude folder", "文件名" to "File name", "地址" to "Location",
    "打开方式选择" to "Choose app", "编辑图片" to "Edit photo", "返回相册" to "Back to albums",
    "收藏" to "Favorite", "取消收藏所选" to "Unfavorite selected", "移到回收站" to "Move to Trash", "菜单" to "Menu", "壁纸" to "Wallpaper",
    "播放速度" to "Playback speed", "倍速" to "Speed", "画中画" to "Picture-in-picture",
    "后台播放" to "Background playback", "锁定控制" to "Lock controls", "解锁控制" to "Unlock controls",
    "旋转方向" to "Orientation", "自适应" to "Adaptive", "横屏" to "Landscape", "竖屏" to "Portrait",
    "顺序播放" to "Play in order", "循环播放" to "Repeat one", "随机播放" to "Shuffle", "播完暂停" to "Stop after current",
    "关闭幻灯片" to "Close slideshow", "上一张" to "Previous", "下一张" to "Next",
    "保存编辑" to "Save edits", "保留二者" to "Keep both", "替换原图" to "Replace original",
    "保留原图并创建编辑副本，或直接替换当前图片。" to "Keep the original and create an edited copy, or replace the current photo.",
    "添加文字" to "Add text", "文字内容" to "Text", "保存中" to "Saving", "分辨率" to "Resolution",
    "输出分辨率" to "Output resolution", "图片质量" to "Image quality", "重置当前工具" to "Reset current tool",
    "撤销" to "Undo", "重做" to "Redo", "构图" to "Crop", "滤镜" to "Filters", "调整" to "Adjust",
    "涂鸦" to "Draw", "文字" to "Text", "左转" to "Rotate left", "右转" to "Rotate right",
    "水平翻转" to "Flip horizontally", "垂直翻转" to "Flip vertically", "校正" to "Straighten",
    "自定义裁剪比例" to "Custom crop ratio", "宽" to "Width", "高" to "Height",
    "曝光" to "Exposure", "亮度" to "Brightness", "对比度" to "Contrast", "色调" to "Tint",
    "色温" to "Temperature", "高光" to "Highlights", "阴影" to "Shadows", "饱和度" to "Saturation",
    "自然饱和度" to "Vibrance", "褪色" to "Fade", "锐度" to "Sharpness", "增强" to "Enhance",
    "设置工具顺序" to "Arrange tools", "设置" to "Settings", "设置构图比例顺序" to "Arrange crop ratios",
    "设置调节选项顺序" to "Arrange adjustment tools", "设置笔型顺序" to "Arrange brush types", "设置字体顺序" to "Arrange fonts",
    "吸管取色" to "Eyedropper", "笔画" to "Brush size", "字号" to "Size", "透明" to "Opacity",
    "描边" to "Stroke", "背景" to "Background", "横向" to "Horizontal", "竖向" to "Vertical",
    "字距" to "Letter spacing", "行距" to "Line spacing", "左对齐" to "Left", "中对齐" to "Center", "右对齐" to "Right",
    "圆珠笔" to "Pen", "钢笔" to "Fountain pen", "毛笔" to "Brush", "马克笔" to "Marker",
    "荧光笔" to "Highlighter", "铅笔" to "Pencil", "蜡笔" to "Crayon", "喷枪" to "Airbrush",
    "霓虹笔" to "Neon", "马赛克" to "Mosaic", "橡皮" to "Eraser",
    "黑体" to "Sans", "宋体" to "Serif", "等宽" to "Monospace", "手写" to "Cursive",
    "原图" to "Original", "自由" to "Free", "本机" to "Device", "自定义" to "Custom",
    "鲜艳" to "Vivid", "暖色" to "Warm", "冷色" to "Cool", "黑白" to "Mono", "胶片" to "Film",
    "回收站" to "Trash", "重复图片" to "Duplicates", "已排除" to "Excluded", "文件归档" to "Archive",
    "返回设置" to "Back to Settings", "全盘查重" to "Scan duplicates", "清理全部" to "Clean all",
    "清理所选" to "Clean selected", "全部还原" to "Restore all", "全部清除" to "Clear all",
    "还原" to "Restore", "没有发现重复图片" to "No duplicate photos found", "没有已排除文件夹" to "No excluded folders",
    "展开全部" to "Expand all", "折叠全部" to "Collapse all", "展开" to "Expand", "折叠" to "Collapse",
    "正在计算文件哈希…" to "Calculating file hashes...", "回收站为空" to "Trash is empty", "恢复扫描" to "Restore scanning",
    "正在分析缩略图…" to "Analyzing thumbnails...", "仅在本机计算感知哈希" to "Perceptual hashes are calculated on this device only",
    "点击右上角扫描" to "Tap Scan in the upper-right", "综合画面、平均色与宽高比" to "Compares content, average color, and aspect ratio",
    "保留最佳" to "Keep best", "选择其余" to "Select others", "建议保留" to "Suggested", "已选择" to "Selected", "未选择" to "Not selected",
    "扫描结果" to "Scan results", "更改" to "Change", "确认文件归档" to "Confirm archive",
    "Pixiv 文件归档" to "Pixiv archive", "打开 Pixiv" to "Open Pixiv", "登录 Pixiv" to "Log in to Pixiv", "已登录 Pixiv" to "Pixiv logged in", "Pixiv 账号" to "Pixiv account", "退出 Pixiv 登录" to "Log out of Pixiv", "更换 Pixiv 账号" to "Switch Pixiv account", "重新登录 Pixiv" to "Log in to Pixiv again", "Pixiv 来源目录" to "Pixiv source folder",
    "文件名不符合 Pixiv 规则" to "Filename does not match Pixiv rules", "无法读取公开作品信息" to "Unable to read public artwork data",
    "等待归档" to "Waiting to archive", "未识别画师" to "Unknown artist", "已确认按 PID 归档" to "Confirmed for PID archive",
    "归档失败，来源文件已保留" to "Archive failed; source file was kept",
    "归档目标目录" to "Archive destination", "将 Pixiv tags 写入图片信息" to "Write Pixiv tags to photo metadata",
    "保留原始文件名" to "Keep original filenames", "扫描 Pixiv 图片" to "Scan Pixiv photos", "开始归档" to "Start archive",
    "正在查询 Pixiv..." to "Querying Pixiv...", "正在归档..." to "Archiving...", "尚未扫描" to "Not scanned",
    "按 PID 归档" to "Archive by PID", "打开 Pixiv 作品" to "Open Pixiv artwork",
    "复制到" to "Copy to", "移动到" to "Move to", "近期使用" to "Recent", "选择文件夹" to "Choose folder",
    "新建文件夹" to "New folder", "文件重名时" to "If a file exists", "保留原文件的修改日期" to "Preserve original modified date",
    "文件夹名称" to "Folder name", "创建" to "Create", "扫描刷新" to "Scan", "添加本地文件夹" to "Add local folder",
    "进入多选" to "Select", "扫描中..." to "Scanning...", "重命名失败" to "Rename failed",
    "分享媒体" to "Share media", "当前系统不支持画中画" to "Picture-in-picture is not supported on this device",
    "清除" to "Clear", "已开启" to "On", "已关闭" to "Off", "查看/编辑 Tags" to "View/Edit tags",
    "视频设置" to "Video settings", "打开视频时自动播放" to "Autoplay videos", "记住最后一次播放进度" to "Remember playback position",
    "自动隐藏播放器界面" to "Auto-hide player controls", "长快进" to "Long skip", "快进长度" to "Skip length",
    "长快进长度" to "Long skip length", "满屏滑动跳过时间" to "Full-screen swipe seek time", "边缘误触保护" to "Edge gesture protection",
    "单击暂停" to "Pause on single tap", "只在竖屏下单击暂停" to "Pause on single tap in portrait only",
    "切换图片和视频" to "Switch photos and videos", "显示全部" to "Show all", "仅显示收藏" to "Favorites only",
    "搜索文件夹、视频名称" to "Search folders and video names", "搜索文件夹、图片名称" to "Search folders and photo names",
    "未选择" to "Not selected"
)
