package com.example.album.ui

import androidx.compose.runtime.compositionLocalOf

val LocalAppEnglish = compositionLocalOf { false }

fun appText(chinese: String, english: Boolean): String = if (english) APP_ENGLISH[chinese] ?: chinese else chinese

fun appSeekText(actionChinese: String, milliseconds: Long, english: Boolean): String {
    val seconds = milliseconds.coerceAtLeast(0L) / 1000L
    val unit = if (english) "s" else "秒"
    return "${appText(actionChinese, english)} $seconds$unit"
}

fun appSeekDeltaText(seconds: Long, english: Boolean): String {
    val sign = if (seconds >= 0L) "+" else ""
    return "$sign$seconds${if (english) "s" else "秒"}"
}

private val APP_ENGLISH = mapOf(
    "请输入文本" to "Enter text",
    "相册" to "Albums", "视频" to "Videos", "时间轴" to "Timeline", "设置" to "Settings",
    "返回" to "Back", "取消" to "Cancel", "确定" to "OK", "应用" to "Apply", "重新应用" to "Re-apply", "保存" to "Save", "保存副本" to "Save copy",
    "完成" to "Done", "关闭" to "Close", "知道了" to "Done", "添加" to "Add", "清除" to "Clear",
    "信息" to "Info", "编辑" to "Edit", "删除" to "Delete", "彻底删除" to "Delete permanently",
    "分享" to "Share", "复制" to "Copy", "移动" to "Move", "重命名" to "Rename",
    "打开方式" to "Open with", "设置为壁纸" to "Set as wallpaper", "幻灯片" to "Slideshow",
    "排除" to "Exclude", "更多操作" to "More actions", "全选" to "Select all", "取消全选" to "Deselect all",
    "收藏所选" to "Favorite selected", "删除所选" to "Delete selected", "复制所选" to "Copy selected",
    "移动所选" to "Move selected", "退出多选" to "Exit selection", "需要照片和视频访问权限" to "Photos and videos permission required",
    "需要照片访问权限" to "Photos permission required", "需要视频访问权限" to "Videos permission required", "授权访问" to "Allow access",
    "授权后才能读取设备上的相册内容。" to "Allow access to read photos and videos on this device.",
    "授权后才能读取设备上的相册内容" to "Allow access to read photos and videos on this device.",
    "没有找到相关内容" to "No matching items", "这里还没有图片" to "No photos yet", "这里还没有视频" to "No videos yet", "此文件夹没有内容" to "This folder is empty",
    // Empty states use one voice: short, and the same shape everywhere.
    "还没有图片" to "No photos yet", "还没有视频" to "No videos yet",
    // Tools entries and the pieces that were added later.
    "壁纸队列" to "Wallpaper queue", "文件清理" to "File cleanup",
    "幻灯片播放" to "Slideshow", "幻灯片队列" to "Slideshow queue",
    "管理静态与动态壁纸队列并应用" to "Manage and apply the static and live wallpaper queues",
    "管理幻灯片队列并开始播放" to "Manage the slideshow queue and start playing",
    "重复图片、回收站与排除文件夹" to "Duplicates, recycle bin and excluded folders",
    "扫描并整理 Pixiv 图片到画师目录" to "Scan and sort Pixiv images into artist folders",
    "加入幻灯片队列" to "Add to slideshow queue", "移出幻灯片队列" to "Remove from slideshow queue",
    "切换" to "Switch", "使用提示" to "Getting around",
    "没有匹配的内容" to "No matching items", "文件夹为空" to "This folder is empty",
    "幻灯片队列为空" to "Slideshow queue is empty", "移出队列" to "Remove",
    "重新扫描" to "Rescan", "清除搜索" to "Clear search", "返回" to "Back",
    "返回工具箱" to "Back to Tools", "返回队列" to "Back to queue",
    "返回上级文件夹" to "Back to parent folder", "退出搜索" to "Leave search",
    "幻灯片设置" to "Slideshow settings", "幻灯片播放间隔" to "Slideshow interval",
    "幻灯片播放动画" to "Slideshow animation", "幻灯片随机播放" to "Shuffle slideshow",
    "列数" to "Columns", "排布方式" to "Layout", "排序方式" to "Sort",
    "进入多选" to "Select", "注意事项" to "Notes", "清空幻灯片队列" to "Clear slideshow queue",
    "媒体" to "Media", "文件夹" to "Folders", "网格" to "Grid", "自适应" to "Adaptive",
    "应用" to "Apply", "取消" to "Cancel", "关闭" to "Close", "完成" to "Done",
    "禁止提示" to "Don't show again",
    "排序方式" to "Sort", "列数" to "Columns", "排布方式" to "Layout", "网格" to "Grid", "自适应" to "Adaptive",
    "媒体" to "Media", "文件夹" to "Folder",
    "时间" to "Date", "名称" to "Name", "大小" to "Size", "数量" to "Count", "时长" to "Duration",
    "升序" to "Ascending", "降序" to "Descending", "覆盖" to "Replace", "跳过" to "Skip", "保留两者" to "Keep both",
    "跳转日期" to "Jump to date", "跳转" to "Jump", "排除文件夹" to "Exclude folder", "文件名" to "File name", "地址" to "Location",
    "打开方式选择" to "Choose app", "编辑图片" to "Edit photo", "返回相册" to "Back to albums", "确认" to "Confirm", "搜索" to "Search", "切换搜索方式" to "Switch search mode", "清除搜索" to "Clear search", "切换为单屏宽度" to "Switch to single-screen width", "切换为多屏宽度" to "Switch to multi-screen width", "使用裁剪区域" to "Use crop area",
    "收藏" to "Favorite", "取消收藏所选" to "Unfavorite selected", "移到回收站" to "Move to Trash", "菜单" to "Menu", "壁纸" to "Wallpaper",
    "播放速度" to "Playback speed", "倍速" to "Speed", "画中画" to "Picture-in-picture",
    "小窗" to "Mini window", "自动小窗" to "Auto mini window", "恢复全屏播放" to "Restore full screen",
    "适配重力" to "Follow sensor", "始终横屏" to "Always landscape", "始终竖屏" to "Always portrait", "按视频比例" to "Match video ratio",
    "亮度：空白：音量 触控占比" to "Brightness/volume touch split", "快退：暂停：快进 触控占比" to "Seek/pause touch split",
    "后台播放" to "Background playback", "锁定控制" to "Lock controls", "解锁控制" to "Unlock controls",
    "旋转方向" to "Orientation", "自适应" to "Adaptive", "横屏" to "Landscape", "竖屏" to "Portrait",
    "顺序播放" to "Play in order", "循环播放" to "Repeat one", "随机播放" to "Shuffle", "播完暂停" to "Stop after current",
    "关闭幻灯片" to "Close slideshow", "上一张" to "Previous", "下一张" to "Next", "恢复全屏播放" to "Resume full-screen playback", "恢复全屏" to "Restore full screen", "幻灯片播放动画" to "Slideshow animation", "幻灯片播放间隔" to "Slideshow interval", "幻灯片设置" to "Slideshow settings", "幻灯片随机播放" to "Shuffle slideshow", "已取消跳转" to "Seek cancelled", "从头播放" to "Play from start", "暂停" to "Pause", "播放" to "Play",
    "保存编辑" to "Save edits", "保留二者" to "Keep both", "替换原图" to "Replace original", "撤回" to "Undo", "点击复原" to "Tap to reset", "点击恢复" to "Tap to restore", "重置构图" to "Reset crop", "重置调整" to "Reset adjustments", "重置涂鸦" to "Reset drawing", "重置文字" to "Reset text",
    "保留原图并创建编辑副本，或直接替换当前图片。" to "Keep the original and create an edited copy, or replace the current photo.",
    "添加文字" to "Add text", "文字内容" to "Text", "保存中" to "Saving", "分辨率" to "Resolution",
    "输出分辨率" to "Output resolution", "图片质量" to "Image quality", "重置当前工具" to "Reset current tool", "重置修改" to "Reset changes",
    "Album 壁纸" to "Album wallpaper", "系统壁纸" to "System wallpaper", "系统壁纸（视频可能不支持）" to "System wallpaper (videos may not be supported)",
    "撤销" to "Undo", "重做" to "Redo", "构图" to "Crop", "滤镜" to "Filters", "调整" to "Adjust",
    "涂鸦" to "Draw", "文字" to "Text", "左转" to "Rotate left", "右转" to "Rotate right",
    "水平翻转" to "Flip horizontally", "垂直翻转" to "Flip vertically", "校正" to "Straighten",
    "自定义裁剪比例" to "Custom crop ratio", "宽" to "Width", "高" to "Height",
    "曝光" to "Exposure", "亮度" to "Brightness", "音量" to "Volume", "对比度" to "Contrast", "色调" to "Tint",
    "色温" to "Temperature", "高光" to "Highlights", "阴影" to "Shadows", "饱和度" to "Saturation",
    "自然饱和度" to "Vibrance", "褪色" to "Fade", "锐度" to "Sharpness", "增强" to "Enhance",
    "设置工具顺序" to "Arrange tools", "设置" to "Settings", "设置构图比例顺序" to "Arrange crop ratios",
    "设置调节选项顺序" to "Arrange adjustment tools", "设置笔型顺序" to "Arrange brush types", "设置字体顺序" to "Arrange fonts",
    "吸管取色" to "Eyedropper", "笔画" to "Brush size", "字号" to "Size", "透明" to "Opacity",
    "描边" to "Stroke", "背景" to "Background", "横向" to "Horizontal", "竖向" to "Vertical",
    "字距" to "Letter spacing", "行距" to "Line spacing", "左对齐" to "Left", "中对齐" to "Center", "右对齐" to "Right",
    "圆珠笔" to "Pen", "钢笔" to "Fountain pen", "毛笔" to "Brush", "马克笔" to "Marker",
    "荧光笔" to "Highlighter", "铅笔" to "Pencil", "蜡笔" to "Crayon", "喷枪" to "Airbrush",
    "霓虹笔" to "Neon", "马赛克" to "Mosaic", "橡皮" to "Eraser",
    "黑体" to "Sans", "宋体" to "Serif", "等宽" to "Monospace", "手写" to "Cursive",
    "原图" to "Original", "自由" to "Free", "本机" to "Device", "自定义" to "Custom",
    "鲜艳" to "Vivid", "暖色" to "Warm", "冷色" to "Cool", "黑白" to "Mono", "胶片" to "Film",
    "回收站" to "Trash", "重复图片" to "Duplicates", "已排除" to "Excluded", "文件归档" to "Archive",
    "返回设置" to "Back to Settings", "全盘查重" to "Scan duplicates", "清理全部" to "Clean all",
    "清理所选" to "Clean selected", "全部还原" to "Restore all", "全部清除" to "Clear all",
    "还原" to "Restore", "没有发现重复图片" to "No duplicate photos found", "没有已排除文件夹" to "No excluded folders",
    "展开全部" to "Expand all", "折叠全部" to "Collapse all", "展开" to "Expand", "折叠" to "Collapse",
    "正在计算文件哈希…" to "Calculating file hashes...", "回收站为空" to "Trash is empty", "恢复扫描" to "Restore scanning",
    "正在分析缩略图…" to "Analyzing thumbnails...", "仅在本机计算感知哈希" to "Perceptual hashes are calculated on this device only",
    "点击右上角扫描" to "Tap Scan in the upper-right", "综合画面、平均色与宽高比" to "Compares content, average color, and aspect ratio",
    "保留最佳" to "Keep best", "选择其余" to "Select others", "建议保留" to "Suggested", "已选择" to "Selected", "未选择" to "Not selected",
    "扫描结果" to "Scan results", "更改" to "Change", "确认文件归档" to "Confirm archive",
    "Pixiv 文件归档" to "Pixiv archive", "打开 Pixiv" to "Open Pixiv", "登录 Pixiv" to "Log in to Pixiv", "已登录 Pixiv" to "Pixiv logged in", "Pixiv 账号" to "Pixiv account", "退出 Pixiv 登录" to "Log out of Pixiv", "更换 Pixiv 账号" to "Switch Pixiv account", "重新登录 Pixiv" to "Log in to Pixiv again", "Pixiv 来源目录" to "Pixiv source folder",
    "文件名不符合 Pixiv 规则" to "Filename does not match Pixiv rules", "无法读取公开作品信息" to "Unable to read public artwork data",
    "等待归档" to "Waiting to archive", "未识别画师" to "Unknown artist", "已确认按 PID 归档" to "Confirmed for PID archive",
    "归档失败，来源文件已保留" to "Archive failed; source file was kept",
    "归档目标目录" to "Archive destination", "将 Pixiv tags 写入图片信息" to "Write Pixiv tags to photo metadata",
    "保留原始文件名" to "Keep original filenames", "扫描 Pixiv 图片" to "Scan Pixiv photos", "开始归档" to "Start archive",
    "正在查询 Pixiv..." to "Querying Pixiv...", "正在归档..." to "Archiving...", "尚未扫描" to "Not scanned", "Pixiv 归档注意事项" to "Pixiv archive notes", "正在确认 Pixiv 登录" to "Checking Pixiv login", "未检测到登录" to "Pixiv login not detected", "文件信息" to "File information", "正在整理媒体库，请稍候" to "Organizing media library, please wait",
    "按 PID 归档" to "Archive by PID", "打开 Pixiv 作品" to "Open Pixiv artwork",
    "复制到" to "Copy to", "移动到" to "Move to", "近期使用" to "Recent", "选择文件夹" to "Choose folder",
    "新建文件夹" to "New folder", "文件夹创建失败" to "Unable to create folder", "没有找到相关文件夹" to "No matching folders", "文件重名时" to "If a file exists", "保留原文件的修改日期" to "Preserve original modified date",
    "文件夹名称" to "Folder name", "创建" to "Create", "扫描刷新" to "Scan", "添加本地文件夹" to "Add local folder",
    "进入多选" to "Select", "扫描中..." to "Scanning...", "重命名失败" to "Rename failed",
    "分享媒体" to "Share media", "当前系统不支持画中画" to "Picture-in-picture is not supported on this device", "加入壁纸队列" to "Add to wallpaper queue", "移出壁纸队列" to "Remove from wallpaper queue", "清空壁纸队列" to "Clear wallpaper queue", "壁纸队列为空" to "Wallpaper queue is empty", "中止" to "Cancel", "播放顺序" to "Playback order", "播放完停止" to "Stop after current", "上一个视频" to "Previous video", "下一个视频" to "Next video", "快退" to "Rewind", "快进" to "Fast-forward", "长快退" to "Long rewind", "锁定控件" to "Lock controls", "解锁控件" to "Unlock controls", "镜像翻转" to "Mirror", "取消镜像" to "Stop mirroring", "无法读取图片" to "Unable to read image", "无法启动后台播放" to "Unable to start background playback",
    "清除" to "Clear", "已开启" to "On", "已关闭" to "Off", "查看/编辑 Tags" to "View/Edit tags",
    "视频设置" to "Video settings", "打开视频时自动播放" to "Autoplay videos", "进入后台时自动暂停" to "Pause in background", "记住最后一次播放进度" to "Remember playback position",
    "自动隐藏播放器界面" to "Auto-hide player controls", "长快进" to "Long skip", "快进长度" to "Skip length",
    "长快进长度" to "Long skip length", "满屏滑动跳过时间" to "Full-screen swipe seek time", "边缘误触保护" to "Edge gesture protection",
    "单击暂停" to "Pause on single tap", "只在竖屏下单击暂停" to "Pause on single tap in portrait only",
    "切换图片和视频" to "Switch photos and videos", "显示全部" to "Show all", "仅显示收藏" to "Favorites only", "网格显示" to "Grid view", "列表显示" to "List view", "清除选中" to "Clear selection", "清空扫描结果" to "Clear scan results", "取消等待" to "Cancel pending", "已归档" to "Archived", "如何处理新图" to "How to handle new images", "重新登录" to "Log in again", "重命名文件夹" to "Rename folder", "自选画笔颜色" to "Custom brush color", "最低" to "Minimum", "最高" to "Maximum", "居左" to "Align left", "居中" to "Center", "居右" to "Align right", "开启" to "On", "图片大小" to "Image size", "行间距" to "Line spacing", "字间距" to "Letter spacing", "视频正在后台播放" to "Video is playing in the background",
    "搜索文件夹、视频名称" to "Search folders and video names", "搜索文件夹、图片名称" to "Search folders and photo names",
    "未选择" to "Not selected",
    // Settings rows. These used to live in a second, private dictionary inside
    // SettingsScreen; keeping one dictionary means a new language only has to
    // be added in one place, and the coverage test below can prove that no
    // appText() call site is missing its English text.
    "开源许可" to "Open-source licenses",
    "清理" to "Cleanup",
    "重复图片、回收站与排除文件夹" to "Duplicates, Trash and excluded folders",
    "主题" to "Theme",
    "主题模式" to "Theme mode",
    "主题颜色" to "Theme color",
    "语言" to "Language",
    "长按移动底栏图标" to "Reorder bottom tabs",
    "长按拖动底栏图标排序" to "Long press a tab to reorder",
    "显示 Pixiv 底栏页面" to "Show Pixiv bottom tab",
    "在底栏显示 Pixiv 页面" to "Show Pixiv as a bottom tab",
    "文件操作" to "File operations",
    "开启后，删除的文件将进入回收站" to "Move deleted files to Trash",
    "回收站文件保留期限" to "Trash retention",
    "保存在应用私有目录，卸载时会一并删除" to "Kept in app storage; uninstalling removes it",
    "导出应用数据" to "Export app data",
    "收藏、队列与偏好设置，不含媒体和账号" to "Favorites and settings; no media or account data",
    "导入应用数据" to "Import app data",
    "会覆盖当前数据" to "Replaces the current data",
    "所有文件访问权限" to "All files access",
    "已开启，归档可直接写入目录" to "Enabled; archive can write directly to folders",
    "未开启，点击前往系统设置授权" to "Not enabled; tap to grant access in system settings",
    "媒体管理权限" to "Media management access",
    "修改或删除媒体文件无需系统反复确认" to "Avoid repeated system prompts when changing media",
    "已开启，删除时使用应用内确认弹窗" to "Enabled; deletion uses the in-app confirmation",
    "删除前确认" to "Confirm before deleting",
    "普通删除是否二次确认" to "Ask before deleting",
    "复制/移动/编辑时保留原日期" to "Keep the original date",
    "编辑后保存方式" to "Save edited photos",
    "保留编辑副本或替换当前版本，保存前均需确认" to "Keep a copy or replace the current version",
    "复制/移动文件已存在" to "When a file already exists",
    "同名文件处理" to "Duplicate filename handling",
    "播放中无操作 3 秒后隐藏控件" to "Hide controls after 3 seconds of inactivity",
    "在播放器中显示长快退和长快进按钮" to "Show long rewind and fast-forward buttons",
    "全屏手势" to "Full-screen gestures",
    "横向滑满整个屏幕对应的进度" to "Time covered by a full-width horizontal swipe",
    "在屏幕边缘松手时取消当次跳转" to "Cancel seeking when released at a screen edge",
    "显示" to "Display",
    "播放 GIF 缩略图" to "Animate GIF thumbnails",
    "仅控制缩略图，预览和全屏始终播放" to "Previews and full screen always remain animated",
    "预览页显示原图" to "Show original photos in preview",
    "先显示缩略图再加载原图" to "Thumbnail first, then the original",
    "显示收藏星标" to "Show favorite stars",
    "显示点号开头的图片" to "Show dot-prefixed images",
    "显示文件名以 . 开头的图片文件" to "Show image files whose names start with .",
    "在缩略图右上角显示收藏星标" to "Show favorite stars on thumbnails",
    "默认排序方式" to "Default sort order",
    "默认界面" to "Default screen",
    "滚动条" to "Scrollbar",
    "下拉刷新" to "Pull to refresh",
    "在支持扫描的页面顶部下拉触发扫描" to "Pull down at the top to rescan",
    "拖动宽度" to "Touch width",
    "调整右侧滚动条的触控区域" to "Adjust the scrollbar touch area",
    "浮现时间" to "Visible duration",
    "停止滚动后继续显示的时间" to "How long the scrollbar remains after scrolling",
    "始终显示" to "Always visible",
    "页面可滚动时保持滚动条常驻" to "Keep the scrollbar visible on scrollable pages",
    "缓存" to "Cache",
    "后台优化" to "Background optimization",
    "在后台增量生成分级缩略图" to "Generate tiered thumbnails incrementally in the background",
    "缓存上限" to "Cache limit",
    "清理缓存" to "Clear cache",
    "关于" to "About",
    "隐私政策" to "Privacy policy",
    "应用版本" to "App version",
    "检查更新" to "Check for updates",
    "自动" to "Automatic",
    "浅色" to "Light",
    "深色" to "Dark",
    "荧光绿" to "Neon green",
    "明亮蓝" to "Bright blue",
    "青绿色" to "Teal",
    "活力橙" to "Orange",
    "珊瑚红" to "Coral",
    "紫罗兰" to "Violet",
    "每次询问" to "Ask every time",
    "自然" to "Natural",
    "淡入淡出" to "Fade",
    "滑动" to "Slide",
    "未添加" to "Not added",
    "已是最新版本" to "Up to date",
    "检查中..." to "Checking..."
)
